<?php

namespace Modera\FoundationBundle\Tests\Functional\Testing;

use Modera\FoundationBundle\Testing\FunctionalTestCase;

/**
 * Here will be tested basic FunctionTestCase backward compatibility behavior.
 *
 * Default isolation level is CLASS
 * Transaction started
 *
 * @author    Alex Plaksin <alex.plaksin@modera.net>
 * @copyright 2015 Modera Foundation
 */
class FunctionalTestCase_BC_CLASS_ISOLATION_Test extends FunctionalTestCase
{
    /**
     * @var int
     */
    private static $setUpRunIterator = 0;

    private static $tearDownIterator = 0;

    private static $transactionStartedIterator = 0;

    private static $transactionRollbackIterator = 0;

    private static $setUpBeforeClassIterator = 0;

    private static $initRunIterator = 0;

    /**
     * Checking:
     * - transaction is started
     * - doTearDown = 0
     * - doSetup = 1.
     */
    public function testOne()
    {
        $this->assertEquals(1, static::$transactionStartedIterator);
        $this->assertEquals(0, static::$transactionRollbackIterator);
        $this->assertEquals(0, static::$tearDownIterator);
        $this->assertEquals(1, static::$setUpRunIterator);
        $this->assertEquals(1, static::$setUpBeforeClassIterator);
        $this->assertEquals(1, static::$initRunIterator);
        $this->assertEquals(static::IM_CLASS, $this->getIsolationLevel());
        $this->assertInstanceOf('Symfony\Component\HttpKernel\KernelInterface', static::$kernel);
        $this->assertInstanceOf('Doctrine\ORM\EntityManager', static::$em);
    }

    public function testTwo()
    {
        $this->assertEquals(1, static::$transactionStartedIterator);
        $this->assertEquals(0, static::$transactionRollbackIterator);
        $this->assertEquals(1, static::$tearDownIterator);
        $this->assertEquals(2, static::$setUpRunIterator);
        $this->assertEquals(1, static::$setUpBeforeClassIterator);
        $this->assertEquals(1, static::$initRunIterator);
    }

    public function testThree()
    {
        $this->assertEquals(1, static::$transactionStartedIterator);
        $this->assertEquals(0, static::$transactionRollbackIterator);
        $this->assertEquals(2, static::$tearDownIterator);
        $this->assertEquals(3, static::$setUpRunIterator);
        $this->assertEquals(1, static::$setUpBeforeClassIterator);
        $this->assertEquals(1, static::$initRunIterator);
    }

    /**
     * Overriding template method to test Case execution.
     */
    public function doSetUp()
    {
        static::$setUpRunIterator++;
    }

    /**
     * Overriding template method to test Case execution.
     */
    public function doTearDown()
    {
        static::$tearDownIterator++;
    }

    protected static function makeTransactionStartDecision()
    {
        static::$transactionStartedIterator++;
    }

    protected static function rollbackTransaction()
    {
        static::$transactionRollbackIterator++;
    }

    public static function doSetupBeforeClass()
    {
        static::$setUpBeforeClassIterator++;
    }

    public static function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        static::$initRunIterator++;
    }

    protected static function getIsolationLevel()
    {
        return static::IM_CLASS;
    }
}
